### PR TITLE
Fixed broken url to be relative

### PR DESCRIPTION
**Pull request by AlexandreArpin**
The URL in the no-bullshit.html page was broken.

### CODE REVIEW

**Comment by TheJJ** [comment]
Can you link to the `_1` image? The `_0` is outdated and probably doesn't have any use showing any more. Also, the nobullshit-page can be removed as nobody is getting to see it except in the repo ;)

**Comment by AlexandreArpin** [comment]
I can do either - let me know if you'd rather delete the page or show the most recent image.

For what it's worth I thought it was a nice little easter egg :p

**Comment by TheJJ** [comment]
removing it is probably the best option.. if you are interested, you can of course improve the "real" website.

**Comment by AlexandreArpin** [comment]
Sorry about that, totally forgot about it.

Anyways, the file is deleted.

**Comment by TheJJ** [comment]
Thanks ;-)

**Pull request merged**
